---
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/TalkPick_Server
    overwrite: yes

permissions:
  - object: /home/ubuntu/TalkPick_Server/scripts/start-server.sh
    mode: "755"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: ubuntu
