version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/TalkPick_Server

permissions:
  - object: /home/ubuntu/TalkPick_Server
    owner: ubuntu
    group: ubuntu
    mode: 755

  - object: /home/ubuntu/TalkPick_Server/scripts/start-server.sh
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: ubuntu