---
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/TalkPick_Server
    overwrite: yes

permissions:
  - object: /home/ubuntu/TalkPick_Server
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: "755"

hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: ubuntu