services:
  ## talkpick
  talkpick-server:
    image: 718513646976.dkr.ecr.ap-northeast-2.amazonaws.com/talkpick-server:latest
    container_name: talkpick-server
    ports:
      - "8080:8080"
    networks:
      - t4y
    restart: always
    volumes:
      - ./env/.env.properties:/app/config/.env.properties
    environment:
      - SPRING_CONFIG_IMPORT=optional:file:/app/config/.env.properties

  ## adminer
  adminer:
    image: adminer
    container_name: talkpick-db-adminer
    networks:
      - t4y
    restart: always
    ports:
      - "8081:8080"

  ## nginx
  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - t4y
    restart: always
    ports:
      - "443:443"
      - "80:80"
    environment:
        ORIGIN_CERTIFICATE: "${ORIGIN_CERTIFICATE}"
        PRIVATE_CERTIFICATE_KEY: "${PRIVATE_CERTIFICATE_KEY}"
    depends_on:
      - talkpick-server
      - adminer
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d

networks:
  t4y: