services:
  ## talkpick server
  talkpick-server:
    image: hszoo/talkpick-server:latest
    container_name: talkpick-server
    networks:
      - t4y
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - /home/ec2-user/TalkPick_Server/env/.env
      
  ## nginx
  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - t4y
    restart: always
    ports:
      - "443:443"
      - "80:80"
    environment:
        ORIGIN_CERTIFICATE: "${ORIGIN_CERTIFICATE}"
        PRIVATE_CERTIFICATE_KEY: "${PRIVATE_CERTIFICATE_KEY}"
    depends_on:
      - talkpick-server
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
networks:
  t4y:
