services:
  ## talkpick server
  talkpick-server:
    image: hszoo/talkpick-server:latest
    container_name: talkpick-server
    networks:
      - t4y
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - /home/ec2-user/TalkPick_Server/env/.env
      
  ## nginx
  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - t4y
    restart: always
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - talkpick-server
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/docs:/usr/share/nginx/html/docs:ro
      - /etc/ssl/cloudflare:/etc/ssl/cloudflare:ro
networks:
  t4y:
