# ?? ??
jwt.secret=TALKPICKSECRETKEYSJJMHM
jwt.access-expire-time=3600000
server.port=8080

# DB ?? (RDS)
spring.datasource.url=jdbc:mysql://talkpick-db.ch6e226o6fra.ap-northeast-2.rds.amazonaws.com:3306/talkpick_db
spring.datasource.username=admin
spring.datasource.password=talkpickadmin!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ??
spring.jpa.hibernate.ddl-auto=update

# Connection Pool ??
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000

# File Upload ??
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Tomcat Thread ??
server.tomcat.threads.max=200
server.tomcat.accept-count=100

# Jasypt ??
jasypt.admin.secret-key=TalkPick_Security_Admin
jasypt.member.secret-key=TalkPick_Security_Member
jasypt.algorithm=PBEWithMD5AndDES
jasypt.pool-size=2

# Kakao API ??
kakao.client-id=a2dc39c8d286ef9fbd7baf1192d34c9c
kakao.redirect-uri=http://localhost:8082/api/v1/topic/kakao
kakao.response-type=code

# LLM ??
llm.base-url=http://localhost:8000

# health check url
healthcheck.url=http://localhost:8080